# Etapa de construcción del frontend
FROM node:20-alpine

# Establecer el directorio de trabajo
WORKDIR /Blitzvideo-ModeradoresVisualizer/app


RUN echo 'npm install' > /start.sh
RUN echo 'node_modules/@angular/cli/bin/ng.js serve --host 0.0.0.0 --port 3003' >> /start.sh

CMD sh /start.sh
