# Dockerfile-Auth

# Etapa de construcción del frontend
FROM node:20-alpine AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY Blitzvideo-Auth/package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el código fuente
COPY Blitzvideo-Auth/ .

# Construir la aplicación Angular
RUN npm run build  # Este comando debe generar dist/b-auth/browser

# Etapa de producción
FROM nginx:alpine

# Copiar los archivos construidos desde la etapa de construcción
COPY --from=build /app/dist/blitzvideo-auth/browser /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

# Comando por defecto para ejecutar nginx
CMD ["nginx", "-g", "daemon off;"]
